---
stages:
  - build
  - test
  - publish
  - deploy

before_script:
  - docker info
  - echo "Running pipeline for $CI_PIPELINE_ID"

build_image:
  stage: build
  script:
    - docker build -t planningpoker:${CI_PIPELINE_ID} ./
    - docker tag planningpoker:${CI_PIPELINE_ID} registry.stangier.io/planningpoker/planningpoker:${CI_PIPELINE_ID}

unit_test:
  stage: test
  script:
    - docker run --rm planningpoker:${CI_PIPELINE_ID} test

publish_to_registry:
  stage: publish
  script:
    - docker push registry.stangier.io/planningpoker/planningpoker:${CI_PIPELINE_ID}
  only:
    - master

run_on_docker:
  stage: deploy
  script:
    - docker stop planningpoker || true
    - docker rm planningpoker || true
    - docker run -d --name=planningpoker -e VIRTUAL_HOST='planningpoker.cc' --label=traefik.backend=planningpoker --label=traefik.frontend.rule=Host:planningpoker.cc --label=traefik.enable=true --label=traefik.port=8080 registry.stangier.io/planningpoker/planningpoker:${CI_PIPELINE_ID} run
  only:
    - master
